ID = "2PGH"
NACCESS_PATH = "../naccess/for_student/naccess"

PDB_BASE_URL = "https://files.rcsb.org/download/"
FASTA_BASE_URL = "https://www.rcsb.org/fasta/entry/"

[AMINO_ACID_WEIGHTS]
A = 89.1
R = 174.2
N = 132.1
D = 133.1
C = 121.2
E = 147.1
Q = 146.2
G = 75.1
H = 155.2
I = 131.2
L = 131.2
K = 146.2
M = 149.2
F = 165.2
P = 115.1
S = 105.1
T = 119.1
W = 204.2
Y = 181.2
V = 117.1
	
[AMINO_ACID_CODES]
ALA = "A"
ARG = "R"
ASN = "N"
ASP = "D"
CYS = "C"
GLU = "E"
GLN = "Q"
GLY = "G"
HIS = "H"
ILE = "I"
LEU = "L"
LYS = "K"
MET = "M"
PHE = "F"
PRO = "P"
SER = "S"
THR = "T"
TRP = "W"
TYR = "Y"
VAL = "V"
